version: '3'

volumes:
  pg_data:
  static:
  media_value:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: on-failure
  backend:
    image: fonkeep/foodgram_backend
    env_file: .env
    volumes:
      - static:/static
      - media_value:/app/media
    depends_on:
      - db
    restart: on-failure
  frontend:
    image: fonkeep/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
    depends_on:
      - backend
    restart: on-failure
  gateway:
    image: fonkeep/foodgram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media_value:/media
    restart: on-failure
